### ISSUE TITLE
FabricProxyLite is not compatible with carpet's /player command

### ISSUE THREAD

**Issue by QPCrummer** [OKTW-Network/FabricProxy-Lite#16]
Here is the error:
```
[21:08:43] [Server thread/ERROR]: Command exception: /player Steve spawn
java.lang.NullPointerException: Cannot invoke "java.net.InetSocketAddress.getAddress()" because the return value of "net.minecraft.class_2535.method_10755()" is null
	at one.oktw.FabricProxyLite.lambda$onInitializeServer$0(FabricProxyLite.java:33) ~[FabricProxyLite-1.1.6.jar:?]
	at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$2(ServerPlayConnectionEvents.java:48) ~[fabric-networking-api-v1-1.0.19+d7c144a865-27ddd48d544c3695.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.onClientReady(ServerPlayNetworkAddon.java:65) ~[fabric-networking-api-v1-1.0.19+d7c144a865-27ddd48d544c3695.jar:?]
	at net.minecraft.class_3324.handler$cje000$handlePlayerConnection(class_3324.java:4463) ~[server-intermediary.jar:?]
	at net.minecraft.class_3324.method_14570(class_3324.java:191) ~[server-intermediary.jar:?]
	at carpet.patches.EntityPlayerMPFake.createFake(EntityPlayerMPFake.java:65) ~[fabric-carpet-1.18.1-1.4.57+v220119.jar:?]
	at carpet.commands.PlayerCommand.spawn(PlayerCommand.java:319) ~[fabric-carpet-1.18.1-1.4.57+v220119.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[brigadier-1.0.18.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:177) ~[brigadier-1.0.18.jar:?]
	at net.minecraft.class_2170.method_9249(class_2170.java:262) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_14370(class_3244.java:1229) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_31286(class_3244.java:1213) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_12048(class_3244.java:1196) ~[server-intermediary.jar:?]
	at net.minecraft.class_2797.method_12115(class_2797.java:30) ~[server-intermediary.jar:?]
	at net.minecraft.class_2797.method_11054(class_2797.java:7) ~[server-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[server-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.redirect$zdk000$redirectExecuteTask(class_1255.java:521) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:10748) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:756) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:134) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:741) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zgm000$modifiedRunLoop(MinecraftServer.java:3365) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:663) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by james58899** [comment]
Can't reproduce.

![](https://user-images.githubusercontent.com/5798637/152644174-783cf6af-d001-46be-8ebf-b3e0a022f19c.png)

**Comment by QPCrummer** [comment]
It works fine now. I think it was a carpet issue
