### ISSUE TITLE
Worker-Main died: java.lang.IllegalArgumentException: Name and ID cannot both be blank

### ISSUE THREAD

**Issue by seb303** [OKTW-Network/FabricProxy-Lite#17]
Since putting our 1.17 Fabric SMP behind a Velocity proxy, running FabricProxy-Lite-1.1.5.jar we are seeing these errors in the log files..

We are also running voicechat mod, which bypasses the proxy (TCP connection on a different port), which could be a factor.

Sometimes after a user logs in (but not every time)
```
[12:05:43] [Server thread/INFO]: Tatsu_Del[/49.49.234.158:58728] logged in with entity id 431 at (514.9256645785099, 63.0, 216.30000001192093)
[12:05:43] [Server thread/WARN]: Player Tatsu_Del can't receive direct packet, using nbt packet instead
[12:05:43] [Server thread/INFO]: Tatsu_Del joined the game
[12:05:48] [Worker-Main-22/WARN]: Worker-Main-22 died
java.lang.IllegalArgumentException: Name and ID cannot both be blank
        at com.mojang.authlib.GameProfile.<init>(GameProfile.java:26) ~[server-intermediary.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:199) ~[server-intermediary.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:186) ~[server-intermediary.jar:?]
        at net.minecraft.class_2631.method_37469(class_2631.java:144) ~[server-intermediary.jar:?]
        at net.minecraft.class_156.method_17974(class_156.java:448) ~[server-intermediary.jar:?]
        at net.minecraft.class_2631.method_37466(class_2631.java:139) ~[server-intermediary.jar:?]
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1434) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
[12:05:48] [Worker-Main-22/ERROR]: Caught exception in thread Thread[Worker-Main-22,5,main]
java.lang.IllegalArgumentException: Name and ID cannot both be blank
        at com.mojang.authlib.GameProfile.<init>(GameProfile.java:26) ~[server-intermediary.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:199) ~[server-intermediary.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:186) ~[server-intermediary.jar:?]
        at net.minecraft.class_2631.method_37469(class_2631.java:144) ~[server-intermediary.jar:?]
        at net.minecraft.class_156.method_17974(class_156.java:448) ~[server-intermediary.jar:?]
        at net.minecraft.class_2631.method_37466(class_2631.java:139) ~[server-intermediary.jar:?]
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1434) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
```

Sometimes just happens any time:
```
[12:29:33] [Worker-Main-24/WARN]: Worker-Main-24 died
java.lang.IllegalArgumentException: Name and ID cannot both be blank
        at com.mojang.authlib.GameProfile.<init>(GameProfile.java:26) ~[server-intermediary.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:199) ~[server-intermediary.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:186) ~[server-intermediary.jar:?]
        at net.minecraft.class_2631.method_37469(class_2631.java:144) ~[server-intermediary.jar:?]
        at net.minecraft.class_156.method_17974(class_156.java:448) ~[server-intermediary.jar:?]
        at net.minecraft.class_2631.method_37466(class_2631.java:139) ~[server-intermediary.jar:?]
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1434) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
[12:29:33] [Worker-Main-24/ERROR]: Caught exception in thread Thread[Worker-Main-24,5,main]
java.lang.IllegalArgumentException: Name and ID cannot both be blank
        at com.mojang.authlib.GameProfile.<init>(GameProfile.java:26) ~[server-intermediary.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:199) ~[server-intermediary.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:186) ~[server-intermediary.jar:?]
        at net.minecraft.class_2631.method_37469(class_2631.java:144) ~[server-intermediary.jar:?]
        at net.minecraft.class_156.method_17974(class_156.java:448) ~[server-intermediary.jar:?]
        at net.minecraft.class_2631.method_37466(class_2631.java:139) ~[server-intermediary.jar:?]
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1434) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
```

**Comment by james58899** [comment]
I don't think FabricProxy-Lite will cause this issue, please check if other mods are trying to get player head with blank name.

**Comment by seb303** [comment]
Ah, do you think it's related to player heads?  We do have player head drops datapack, and we also have Bedrock clients joining via Geyser on the proxy.  Maybe the Bedrock player heads are the problem...

**Comment by seb303** [comment]
I've done some further testing on the server and have narrowed the problem down to player heads from Bedrock clients which had been placed as blocks.  The error occurs when connecting to the server while in the area of the placed heads, or when moving into chunk-loading range of the heads.

So confirmed that it is not related to FabricProxy-Lite.

Thanks @james58899 for pointing me in the right direction.
