### ISSUE TITLE
Connection cannot get established in v2.3.0 when bein a operator

### ISSUE THREAD

**Issue by michiruf** [OKTW-Network/FabricProxy-Lite#39]
I have tried to set up velocity with this plugin installed on my fabric nodes, and everything works fine.
But when I set myself to be an operator, connections to the node cannot get established.
In my opinion, this makes it not usable on any online server and I would consider this bug as mandatory.

Velocity 3.1.2-SNAPSHOT with build 200 was used. In any case it would matter, the secret was set to 'TEST'. The other 3 'hack' parameters were tried in any combination possible.

Error message:
```
[xx:xx:xx ERROR]: [server connection] USERNAME -> building: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@4ab24caa
minecraft-cluster_router | io.netty.handler.codec.CorruptedFrameException: Error decoding class com.velocitypowered.proxy.protocol.packet.AvailableCommands Direction CLIENTBOUND Protocol 1.19.1 State PLAY ID f
minecraft-cluster_router |      at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.handleDecodeFailure(MinecraftDecoder.java:128) ~[velocity-3.1.2-SNAPSHOT-200.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
minecraft-cluster_router |      at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:83) ~[velocity-3.1.2-SNAPSHOT-200.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
minecraft-cluster_router |      at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:58) ~[velocity-3.1.2-SNAPSHOT-200.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
minecraft-cluster_router |      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.1.2-SNAPSHOT-200.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
minecraft-cluster_router |      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.1.2-SNAPSHOT-200.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
minecraft-cluster_router |      at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.1.2-SNAPSHOT-200.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
minecraft-cluster_router |      at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity-3.1.2-SNAPSHOT-200.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
minecraft-cluster_router |      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.1.2-SNAPSHOT-200.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
minecraft-cluster_router |      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.1.2-SNAPSHOT-200.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
minecraft-cluster_router |      at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.1.2-SNAPSHOT-200.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
minecraft-cluster_router |      at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity-3.1.2-SNAPSHOT-200.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
minecraft-cluster_router |      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity-3.1.2-SNAPSHOT-200.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
minecraft-cluster_router |      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.1.2-SNAPSHOT-200.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
minecraft-cluster_router |      at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.1.2-SNAPSHOT-200.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
minecraft-cluster_router |      at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity-3.1.2-SNAPSHOT-200.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
minecraft-cluster_router |      at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[velocity-3.1.2-SNAPSHOT-200.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
minecraft-cluster_router |      at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[velocity-3.1.2-SNAPSHOT-200.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
minecraft-cluster_router |      at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[velocity-3.1.2-SNAPSHOT-200.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
minecraft-cluster_router |      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.1.2-SNAPSHOT-200.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
minecraft-cluster_router |      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.1.2-SNAPSHOT-200.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
minecraft-cluster_router |      at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.1.2-SNAPSHOT-200.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
minecraft-cluster_router |      at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity-3.1.2-SNAPSHOT-200.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
minecraft-cluster_router |      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity-3.1.2-SNAPSHOT-200.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
minecraft-cluster_router |      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.1.2-SNAPSHOT-200.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
minecraft-cluster_router |      at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity-3.1.2-SNAPSHOT-200.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
minecraft-cluster_router |      at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[velocity-3.1.2-SNAPSHOT-200.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
minecraft-cluster_router |      at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[velocity-3.1.2-SNAPSHOT-200.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
minecraft-cluster_router |      at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[velocity-3.1.2-SNAPSHOT-200.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
minecraft-cluster_router |      at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.1.2-SNAPSHOT-200.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
minecraft-cluster_router |      at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.1.2-SNAPSHOT-200.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
minecraft-cluster_router |      at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.1.2-SNAPSHOT-200.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
minecraft-cluster_router |      at java.lang.Thread.run(Thread.java:833) ~[?:?]
minecraft-cluster_router | Caused by: java.lang.IllegalArgumentException: Argument type identifier null unknown.
minecraft-cluster_router |      at com.velocitypowered.proxy.protocol.packet.brigadier.ArgumentPropertyRegistry.deserialize(ArgumentPropertyRegistry.java:85) ~[velocity-3.1.2-SNAPSHOT-200.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
minecraft-cluster_router |      at com.velocitypowered.proxy.protocol.packet.AvailableCommands.deserializeNode(AvailableCommands.java:208) ~[velocity-3.1.2-SNAPSHOT-200.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
minecraft-cluster_router |      at com.velocitypowered.proxy.protocol.packet.AvailableCommands.decode(AvailableCommands.java:86) ~[velocity-3.1.2-SNAPSHOT-200.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
minecraft-cluster_router |      at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:81) ~[velocity-3.1.2-SNAPSHOT-200.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
minecraft-cluster_router |      ... 30 more
[xx:xx:xx INFO]: [connected player] USERNAME (<ip address withheld>) has disconnected: Your connection to building encountered a problem.
```

**Comment by james58899** [comment]
Read https://docs.papermc.io/velocity/server-compatibility#fabric , you need install CrossStitch.

**Comment by michiruf** [comment]
That worked well, thank you for this work. IMO you should really consider mentioning this in your readme
