### ISSUE TITLE
Some players cannot join with different version from the server

### ISSUE THREAD

**Issue by Glucy-2** [OKTW-Network/FabricProxy-Lite#40]
* 1.19.2 Client
* Velocity with ViaVersion and ViaBackwards
* 1.19.3 fabric server with FabricProxy-Lite 2.4.0

log on fabric server:
````py
[13:15:27] [Server thread/INFO]: Disconnecting /121.x.x.185(Velocity IP):59320: Unable to verify player details
[13:15:27] [Server thread/INFO]: /121.x.x.185(Velocity IP):59320 lost connection: Unable to verify player details
[13:15:30] [Server thread/ERROR]: Secret check failed.
java.lang.IllegalStateException: Unsupported forwarding version 3, supported [1, 4]
       at one.oktw.VelocityLib.checkVersion(VelocityLib.java:54) ~[FabricProxy-Lite-2.4.0.jar:?]
       at one.oktw.PacketHandler.lambda$handleVelocityPacket$0(PacketHandler.java:36) ~[FabricProxy-Lite-2.4.0.jar:?]
       at net.minecraft.class_1255.method_5386(class_1255.java:67) ~[server-intermediary.jar:?]
       at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
       at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
       at net.minecraft.class_1255.redirect$zek000$redirectExecuteTask(class_1255.java:521) ~[server-intermediary.jar:?]
       at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
       at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:15800) ~[server-intermediary.jar:?]
       at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:763) ~[server-intermediary.jar:?]
       at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[server-intermediary.jar:?]
       at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:748) ~[server-intermediary.jar:?]
       at net.minecraft.server.MinecraftServer.handler$zhk000$modifiedRunLoop(MinecraftServer.java:4417) ~[server-intermediary.jar:?]
       at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:655) ~[server-intermediary.jar:?]
       at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264) ~[server-intermediary.jar:?]
       at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13:15:30] [Server thread/INFO]: Disconnecting /121.x.x.185:59328: Unable to verify player details
[13:15:30] [Server thread/INFO]: /121.x.x.185:59328 lost connection: Unable to verify player details
````

**Comment by DominoWWW** [comment]
Yes, support 1.19-1.19.2 servers would be quite nice!

**Comment by gadget78** [comment]
would this be the reason for floodgate having issues with this ??

**Comment by Glucy-2** [comment]
> would this be the reason for floodgate having issues with this ??

What do u mean, I am using floodgate but this issue doesn't seem to be related

**Comment by warmbroke** [comment]
```
diff --git a/proxy/src/main/java/com/velocitypowered/proxy/connection/backend/LoginSessionHandler.java b/proxy/src/main/java/com/velocitypowered/proxy/connection/backend/LoginSessionHandler.java
index 8495a878..fcc80b06 100644
--- a/proxy/src/main/java/com/velocitypowered/proxy/connection/backend/LoginSessionHandler.java
+++ b/proxy/src/main/java/com/velocitypowered/proxy/connection/backend/LoginSessionHandler.java
@@ -187,7 +187,7 @@ public class LoginSessionHandler implements MinecraftSessionHandler {
             ? VelocityConstants.MODERN_LAZY_SESSION
             : VelocityConstants.MODERN_FORWARDING_DEFAULT;
       }
-      if (player.getIdentifiedKey() != null) {
+      if (false && player.getIdentifiedKey() != null) {
         // No enhanced switch on java 11
         switch (player.getIdentifiedKey().getKeyRevision()) {
           case GENERIC_V1:
```

Just patch out forwarding version 2 and 3 directly in velocity. This is the easiest way.

**Comment by RealKomander** [comment]
> ```
> diff --git a/proxy/src/main/java/com/velocitypowered/proxy/connection/backend/LoginSessionHandler.java b/proxy/src/main/java/com/velocitypowered/proxy/connection/backend/LoginSessionHandler.java
> index 8495a878..fcc80b06 100644
> --- a/proxy/src/main/java/com/velocitypowered/proxy/connection/backend/LoginSessionHandler.java
> +++ b/proxy/src/main/java/com/velocitypowered/proxy/connection/backend/LoginSessionHandler.java
> @@ -187,7 +187,7 @@ public class LoginSessionHandler implements MinecraftSessionHandler {
>              ? VelocityConstants.MODERN_LAZY_SESSION
>              : VelocityConstants.MODERN_FORWARDING_DEFAULT;
>        }
> -      if (player.getIdentifiedKey() != null) {
> +      if (false && player.getIdentifiedKey() != null) {
>          // No enhanced switch on java 11
>          switch (player.getIdentifiedKey().getKeyRevision()) {
>            case GENERIC_V1:
> ```
> 
> Just patch out forwarding version 2 and 3 directly in velocity. This is the easiest way.

What does this mean? I have the same bug, how to fix it?

**Comment by RealKomander** [comment]
please help!

**Comment by james58899** [comment]
Closed, as this is an old issue and unlikely to be fixed.
