### ISSUE TITLE
Seems incompatible with cross-version mods like ViaFabric?

### ISSUE THREAD

**Issue by ThymeChen** [OKTW-Network/FabricProxy-Lite#43]
Player kicked : `(Velocity) disconnected while connecting to survive: Unable to verify player details`

Minecraft Server : 1.19.3 with ViaFabric and ViaBackwards
FabricProxy-Lite : 2.4.0
Minecraft Client : 1.19.1
Velocity : 3.2.0-SNAPSHOT

``` log
(Minecraft Server)
[11:47:14 ERROR] [Server thread]: [PacketHandler] Secret check failed.
java.lang.IllegalStateException: Unsupported forwarding version 3, supported [1, 4]
        at one.oktw.VelocityLib.checkVersion(VelocityLib.java:54) ~[FabricProxy-Lite-2.4.0.jar:?]
        at one.oktw.PacketHandler.lambda$handleVelocityPacket$0(PacketHandler.java:36) ~[FabricProxy-Lite-2.4.0.jar:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:67) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.redirect$zep000$redirectExecuteTask(BlockableEventLoop.java:521) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:130) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:8300) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:763) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:139) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:748) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zhg000$modifiedRunLoop(MinecraftServer.java:3917) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:655) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:264) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by james58899** [comment]
#40
