### ISSUE TITLE
NBT Tags too large

### ISSUE THREAD

**Issue by LandonDeam** [OKTW-Network/FabricProxy-Lite#59]
Trying to setup a Velocity/Fabric server with the [Dogcraft](https://modrinth.com/modpack/dogcraft-official) modpack, and I get the following error anytime I try to connect through FabricProxy-Lite and Velocity
```
[21:24:53] [Server thread/INFO]: Player[/MyIP:APort] logged in with entity id 104 at (2.5, 64.0, -66.5)
[21:24:53] [Server thread/INFO]: Sending server config values to client
[21:24:53] [Server thread/ERROR]: Couldn't place player in world
java.lang.IllegalArgumentException: Payload may not be larger than 1048576 bytes
        at net.minecraft.class_2658.<init>(class_2658.java:39) ~[server-intermediary.jar:?]
        at net.fabricmc.fabric.impl.networking.server.ServerNetworkingImpl.createPlayC2SPacket(ServerNetworkingImpl.java:45) ~[fabric-networking-api-v1-1.2.11+10eb22f490-f06f04cf50fd31dd.jar:?]
        at net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking.createS2CPacket(ServerPlayNetworking.java:211) ~[fabric-networking-api-v1-1.2.11+10eb22f490-f06f04cf50fd31dd.jar:?]
        at net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking.send(ServerPlayNetworking.java:250) ~[fabric-networking-api-v1-1.2.11+10eb22f490-f06f04cf50fd31dd.jar:?]
        at net.fabricmc.fabric.impl.registry.sync.packet.RegistryPacketHandler.sendPacket(RegistryPacketHandler.java:52) ~[fabric-registry-sync-v0-0.9.32+9244241690-ca0baa6c1ff924d0.jar:?]
        at net.fabricmc.fabric.impl.registry.sync.packet.NbtRegistryPacketHandler.sendPacket(NbtRegistryPacketHandler.java:52) ~[fabric-registry-sync-v0-0.9.32+9244241690-ca0baa6c1ff924d0.jar:?]
        at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.sendPacket(RegistrySyncManager.java:96) ~[fabric-registry-sync-v0-0.9.32+9244241690-ca0baa6c1ff924d0.jar:?]
        at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.sendPacket(RegistrySyncManager.java:88) ~[fabric-registry-sync-v0-0.9.32+9244241690-ca0baa6c1ff924d0.jar:?]
        at net.fabricmc.fabric.impl.registry.sync.FabricRegistryInit.lambda$onInitialize$0(FabricRegistryInit.java:30) ~[fabric-registry-sync-v0-0.9.32+9244241690-ca0baa6c1ff924d0.jar:?]
        at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$2(ServerPlayConnectionEvents.java:48) ~[fabric-networking-api-v1-1.2.11+10eb22f490-f06f04cf50fd31dd.jar:?]
        at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.onClientReady(ServerPlayNetworkAddon.java:65) ~[fabric-networking-api-v1-1.2.11+10eb22f490-f06f04cf50fd31dd.jar:?]
        at net.minecraft.class_3324.handler$cog000$fabric-networking-api-v1$handlePlayerConnection(class_3324.java:7013) ~[server-intermediary.jar:?]
        at net.minecraft.class_3324.method_14570(class_3324.java:200) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.method_33800(class_3248.java:151) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.method_14384(class_3248.java:138) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.redirect$coh000$fabric-networking-api-v1$handlePlayerJoin(class_3248.java:563) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.method_18784(class_3248.java:73) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10754(class_2535.java:248) ~[server-intermediary.jar:?]
        at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:289) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:1623) [?:?]
[21:24:53] [Server thread/INFO]: Player lost connection: Invalid player data
[21:24:53] [Server thread/INFO]: Player left the game
[21:24:53] [Server thread/INFO]: Updating all forceload tickets for d4527f3b-d015-4d85-8dd5-9004b7941320
[21:24:53] [Server thread/INFO]: Disconnecting client Player
[21:24:53] [Server thread/WARN]: handleDisconnection() called twice
```
I tried joining on vanilla with just FabricAPI, FabricProxy-Lite, and Crossstitch, and it worked fine, so I can fairly confidently say that it's an issue related to one of the mods. I'm working on figuring out what mod _exactly_ is causing this, but it's going to be a long search (250 mods in this pack).

**Comment by LandonDeam** [comment]
After doing some more digging, it would appear that the mods Chipped, Consistency+, Continuity, and Create Deco are partially behind this. Removing them from my modpack stops the issue on join. However, it is still fairly concerning that at least one other mod is creating ~2MB worth of NBT data, because they only add a few bytes over the limit.

**Comment by LandonDeam** [comment]
Did more testing, error occurs even without FabricProxy-Lite, so it _is_ a Velocity issue. Sorry for the trouble, closing.
