### ISSUE TITLE
Player kicked with Internal Exception: io.netty.handler.codec.DecoderException:

### ISSUE THREAD

**Issue by PapuutekAPT** [OKTW-Network/FabricProxy-Lite#66]
- Minecraft 1.20.2
- Velocity (3.2.0-SNAPSHOT) with no plugins,
- Fabric Loader 1.14.24

### Client mods:
- Fabric API 0.90.7

### Server mods:
- fabric API 0.90.7
- FabricProxyLite 2.7.0

---

When joining to server sometimes player is kicked due to:
```
Player lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(2) + length(8) exceeds writerIndex(5): PooledUnsafeDirectByteBuf(ridx: 2, widx: 5, cap: 5)
```

Logs from Velocity are as poor as
```
You were kicked from main: disconnect.genericReason
```
but sometimes, always after above error occurs that happens:
```
[22:21:43] [Netty epoll Worker #19/ERROR] [com.velocitypowered.proxy.connection.client.ConnectedPlayer]: [connected player] Player (/172.19.0.1:53458): unable to connect to server main
java.io.IOException: Unexpectedly disconnected from remote server
	at com.velocitypowered.proxy.connection.backend.ConfigSessionHandler.disconnected(ConfigSessionHandler.java:208) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at com.velocitypowered.proxy.connection.MinecraftConnection.channelInactive(MinecraftConnection.java:123) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:305) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at com.velocitypowered.proxy.protocol.netty.PlayPacketQueueHandler.channelInactive(PlayPacketQueueHandler.java:81) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:411) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:376) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:305) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:301) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at java.lang.Thread.run(Thread.java:1570) [?:?]
[22:21:43] [Netty epoll Worker #19/INFO] [com.velocitypowered.proxy.connection.client.ConnectedPlayer]: [connected player] Player (/172.19.0.1:53458) has disconnected: Unable to connect you to main. Please try again later.
```

It doesn't matter if i join to the server or just change it to different one.

Problem does not occurs when:
 - Client does not have fabric API or
 - server is running without FabricProxy and Velocity player-info-forwarding-mode is set to none.

## Steps to reproduce:
- Setup server configuration with mods and plugins described above.
- Join and disconnect a few times (frequency doesn't matter).

**Comment by james58899** [comment]
Since this will not happen when the client does not have FabricAPI, this is most likely a issue between Velocity and FabricAPI.
Please open an issue on their repo.
