### ISSUE TITLE
I dont know whats going on

### ISSUE THREAD

**Issue by Skywalker8510** [OKTW-Network/FabricProxy-Lite#69]
so this was all working perfectly fine earlier but I don't know whats going on with it now. on the proxy end it says I'm connected to the server I'm trying to connect to but on the server end it doesn't even see anyone trying to join. i checked to make sure all the port stuff is set correctly and it is I'm not sure whats going on.

**Comment by Skywalker8510** [comment]
it does that or this was something new it just did

https://mclo.gs/USXmLlf

**Comment by Skywalker8510** [comment]
it just did this new thing

> `[20:49:01 INFO]: [server connection] Skywalker8510 -> redstone has connected
[20:53:02 ERROR]: [server connection] Skywalker8510 -> redstone: read timed out
[20:53:02 INFO]: [server connection] Skywalker8510 -> redstone has disconnected
[20:53:02 ERROR]: [connected player] Skywalker8510 (/127.233.128.237:49550): unable to connect to server redstone
java.io.IOException: Unexpectedly disconnected from remote server
	at com.velocitypowered.proxy.connection.backend.TransitionSessionHandler.disconnected(TransitionSessionHandler.java:216) ~[velocity-3.2.0.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at com.velocitypowered.proxy.connection.MinecraftConnection.channelInactive(MinecraftConnection.java:123) ~[velocity-3.2.0.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:305) ~[velocity-3.2.0.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[velocity-3.2.0.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) ~[velocity-3.2.0.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) ~[velocity-3.2.0.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277) ~[velocity-3.2.0.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303) ~[velocity-3.2.0.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[velocity-3.2.0.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) ~[velocity-3.2.0.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:411) ~[velocity-3.2.0.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:376) ~[velocity-3.2.0.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:305) ~[velocity-3.2.0.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[velocity-3.2.0.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) ~[velocity-3.2.0.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405) ~[velocity-3.2.0.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:301) ~[velocity-3.2.0.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[velocity-3.2.0.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901) ~[velocity-3.2.0.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813) ~[velocity-3.2.0.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[velocity-3.2.0.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[velocity-3.2.0.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[velocity-3.2.0.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[velocity-3.2.0.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.2.0.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.2.0.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.2.0.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at java.lang.Thread.run(Thread.java:833) [?:?]`

**Comment by wifi-left** [comment]
`Skywalker8510 -> redstone: read timed out`
It seemed that your proxy can't access to your 'redstone' server.

**Comment by james58899** [comment]
If it was working fine earlier, it wouldn't be this mod that's causing the issue.
