### ISSUE TITLE
Bug with Luckperms that prevents server start

### ISSUE THREAD

**Issue by SexyEis** [OKTW-Network/FabricProxy-Lite#85]
Proxy Config:
hackOnlineMode = true
hackEarlySend = true
hackMessageChain = true
secret = "secret"

Mods on Server:
fabric-api-0.97.0+1.20.4.jar
FabricProxy-Lite-2.7.0.jar
LuckPerms-Fabric-5.4.124.jar

Error:
[21:58:06] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'server' due to errors, provided by 'luckperms'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.10.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.10.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.10.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:64) ~[fabric-loader-0.15.10.jar:?]
        at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.10.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.10.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/networking/v1/LoginPacketSender
        at me.lucko.luckperms.fabric.listeners.FabricConnectionListener.registerListeners(FabricConnectionListener.java:61) ~[LuckPerms-Fabric-5.4.124.jar:?]
        at me.lucko.luckperms.fabric.LPFabricPlugin.registerFabricListeners(LPFabricPlugin.java:88) ~[LuckPerms-Fabric-5.4.124.jar:?]
        at me.lucko.luckperms.fabric.LPFabricBootstrap.onInitializeServer(LPFabricBootstrap.java:142) ~[LuckPerms-Fabric-5.4.124.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.10.jar:?]
        ... 6 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.networking.v1.LoginPacketSender
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.10.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at me.lucko.luckperms.fabric.listeners.FabricConnectionListener.registerListeners(FabricConnectionListener.java:61) ~[LuckPerms-Fabric-5.4.124.jar:?]
        at me.lucko.luckperms.fabric.LPFabricPlugin.registerFabricListeners(LPFabricPlugin.java:88) ~[LuckPerms-Fabric-5.4.124.jar:?]
        at me.lucko.luckperms.fabric.LPFabricBootstrap.onInitializeServer(LPFabricBootstrap.java:142) ~[LuckPerms-Fabric-5.4.124.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.10.jar:?]
        ... 6 more
        
        Ive tried with someone else on a different server but same issue there and we don't know on how to get this fixed. we also deleted configs, mods, redownloaded everything, double checked everything but nothing gets it fixed. Does anyone have an idea?

**Comment by james58899** [comment]
LuckPerms v5.4.124 not support Minecraft 1.20.4.

**Comment by SexyEis** [comment]
But What Version is bc it just says 1.20.x?

**Comment by james58899** [comment]
You can download from https://modrinth.com/mod/luckperms
